server:
  port: 8080
  allowOrigins:
    - "*"
  bodyLimit: "10M"
  timeout: 30 # Changed to string with units for time.Duration

oauth2:
  playerRedirectUrl: "http://localhost:8080/v1/oauth2/google/player/login/callback"
  adminRedirectUrl: "http://localhost:8080/v1/oauth2/google/admin/login/callback"
  clientId: "xxxxx.apps.googleusercontent.com"
  clientSecret: "xxxxx"
  endpoints:
    authUrl: "https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force"
    tokenUrl: "https://oauth2.googleapis.com/token"
    deviceAuthUrl: "https://oauth2.googleapis.com/device/code"
  scopes:
    - "https://www.googleapis.com/auth/userinfo.email"
    - "https://www.googleapis.com/auth/userinfo.profile"
  userInfoUrl: "https://www.googleapis.com/oauth2/v2/userinfo"
  revokeUrl: "https://accounts.google.com/o/oauth2/revoke"

state:
  secret: "xxxxx"
  expiresAt: 120  # Changed to string with units for time.Duration
  isuser: "isekaishop"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: 123456  # Note: In the struct this should be a string, not an int
  dbname: "testdb"
  sslmode: "disable"
  schema: "public"